### ISSUE TITLE
new widget attribute for html attributes

### ISSUE THREAD

**Issue by thet** [conestack/yafowil#12]
while trying to implement every possible html(5) attribute in yafowil (see: https://github.com/bluedynamics/yafowil/tree/html5-attributes ) i found that a seperate namespace for those attributes would be neccassary.
mixing yafowil specific widget attributes like next, handler, error_class, etc and html specific attributes like id, name, class, size, ... in one dictionary might lead into namespace clashes.
therefore i suggest to put yafowil specific attributes and html attributes into seperate variables:

``` yaml:
widgets:
- title:
    factory: label:field:error:text
    value: expr:context.get('title', '')
    attrs:
        label: i18n:Title
        required: True
    props:
        required_message: No title given
        error_class: blabla
```
