### ISSUE TITLE
missing fieldsetname in rendered fieldset id for structural fieldsets

### ISSUE THREAD

**Issue by thet** [conestack/yafowil#6]
the yaml structure

``` yaml
[...]
widgets:
- myAwesomeFieldset:
    factory: fieldset
    props:
        structural: True
    widgets:
[...]
```

renders to

``` html
<fieldset id="fieldset-FORMNAME">
```

instead of

``` html
<fieldset id="fieldset-FORMNAME-myAwesomeFieldset">
```

(the fieldset name is rendered for non-structural fieldsets)

i consider this beeing a bug, since i see no reason, why the fieldset name isn't included in the fieldset id for structural fieldsets.
